### ISSUE TITLE
I just can't load workflow

### ISSUE THREAD

**Issue by harry6661** [numz/Comfyui-FlowChain#11]
[image](https://github.com/user-attachments/assets/63c22b26-99cc-4018-88fd-4876272e9e16)

I think Workflow (FlowChain ⛓️) node recognize workflows saved in ComfyUI\user\default\workflows\api

But when I tried to operate this node, I can't get any outcome except this message;

got prompt
!!! Exception during processing !!! 'workflow'
Traceback (most recent call last):
  File "E:\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 850, in generate
    workflow, _ = get_recursive_workflow(workflows, 5000)
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 828, in get_recursive_workflow
    subworkflow, max_id = get_recursive_workflow(workflow_name, max_id)
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 823, in get_recursive_workflow
    workflow = get_workflow(workflows)
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 605, in get_workflow
    return workflow["workflow"]
KeyError: 'workflow'

got prompt
!!! Exception during processing !!! 'workflow'
Traceback (most recent call last):
  File "E:\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 850, in generate
    workflow, _ = get_recursive_workflow(workflows, 5000)
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 823, in get_recursive_workflow
    workflow = get_workflow(workflows)
  File "E:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 605, in get_workflow
    return workflow["workflow"]
KeyError: 'workflow'

Prompt executed in 0.01 seconds

**Comment by numz** [comment]
Hi, 
sorry for the time pasted...
Sorry about that, I'have updated the extension, update and restart from scratch, old config will no longer works.
Now you must use standart format, (I have remove the dependency to API format) so just use a standart workflow with workflowInput or workfowOutput nodes.
Let me know

Regards
